// Code generated by MockGen. DO NOT EDIT.
// Source: goat/pkg/hn (interfaces: Client)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	hn "goat/pkg/hn"
	reflect "reflect"
)

// MockHnClient is a mock of Client interface
type MockHnClient struct {
	ctrl     *gomock.Controller
	recorder *MockHnClientMockRecorder
}

// MockHnClientMockRecorder is the mock recorder for MockHnClient
type MockHnClientMockRecorder struct {
	mock *MockHnClient
}

// NewMockHnClient creates a new mock instance
func NewMockHnClient(ctrl *gomock.Controller) *MockHnClient {
	mock := &MockHnClient{ctrl: ctrl}
	mock.recorder = &MockHnClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHnClient) EXPECT() *MockHnClientMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockHnClient) Get(arg0 int) hn.Item {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(hn.Item)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockHnClientMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHnClient)(nil).Get), arg0)
}

// Top mocks base method
func (m *MockHnClient) Top() []int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Top")
	ret0, _ := ret[0].([]int)
	return ret0
}

// Top indicates an expected call of Top
func (mr *MockHnClientMockRecorder) Top() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Top", reflect.TypeOf((*MockHnClient)(nil).Top))
}
